default:
  image:
    name: eu.gcr.io/savannah-emr/fls-image:latest

variables:
  GIT_STRATEGY: clone    

stages:
  - test:unit:widgets
  - test:driver
  - deploy

variables:
  BUILD_VERSION_ROOT : "1.0"  
  PACKAGE_NAME : "com.savannah.bewell"
  BUNDLE_FILE_PATH : $CI_PROJECT_DIR/build/app/outputs/bundle/release/app-release.aab
  APP_FILE_PATH : $CI_PROJECT_DIR/build/app/outputs/apk/release/app-release.apk
   

runUnitTests:
  stage: test:unit:widgets
  tags:
    - healthcloud
  script:    
    - flutter upgrade    
    - flutter --version
    - flutter pub get
    - flutter analyze
    - flutter test --coverage tests/unit_tests/ 
    

runWidgetTests:
  stage: test:unit:widgets  
  tags:
    - healthcloud
  script:   
    - flutter upgrade    
    - flutter --version
    - flutter pub get
    - flutter analyze    
    - flutter test --coverage tests/widgets_tests/



.buildRealeaseApp:
  script:
    - set -e
    - echo "=== GENERATINNG KEY PROPERTIES FILE ==="    
    - echo "storePassword=$KEY_STORE_PWD" | tee -a $CI_PROJECT_DIR/android/key.properties 
    - echo "keyPassword=$KEY_PWD" | tee -a $CI_PROJECT_DIR/android/key.properties
    - echo "keyAlias=$KEY_STORE_ALIAS" | tee -a $CI_PROJECT_DIR/android/key.properties
    - echo "storeFile=$CI_PROJECT_DIR/sugar-and-spice-keystore.jks" | tee -a $CI_PROJECT_DIR/android/key.properties   
    - echo "=== BUILDING RELEASE ANDROID APPBUNDLE ==="  
    - flutter upgrade     
    - flutter build appbundle --build-number $CI_JOB_ID --build-name=$BUILD_VERSION_ROOT.$CI_JOB_ID
    - flutter build apk --release --build-number $CI_JOB_ID --build-name=$BUILD_VERSION_ROOT.$CI_JOB_ID
    - firebase appdistribution:distribute $APP_FILE_PATH --app $FIREBASE_APP_ID --groups healthcloud --token $FIREBASE_TOKEN 
   


.publishToInternalTrack:
  stage: deploy
  tags:
    - healthcloud
  only:
    - develop 
  extends: .buildRealeaseApp
  after_script:
    - echo "=== PUBLISHING TO GOOGLE PLAY STORE [INTERNAL TRACK RELEASE] ==="    
    - |
      fls-android track --build-number $CI_JOB_ID --package-name $PACKAGE_NAME \
      --bundle-path $BUNDLE_FILE_PATH --track-name internal
    - |    
  

.publishToAlphaTrack:
  stage: deploy
  tags:
    - healthcloud
  only:
    - alpha  
  extends: .buildRealeaseApp
  after_script:
    - echo "=== PUBLISHING TO GOOGLE PLAY STORE [ALPHA TRACK RELEASE] ==="    
    - |
      fls-android track --build-number $CI_JOB_ID --package-name $PACKAGE_NAME \
      --bundle-path $BUNDLE_FILE_PATH --track-name alpha --status draft
    - |      


.publishToBetaTrack:
  stage: deploy
  tags:
    - healthcloud
  only:
    - beta  
  extends: .buildRealeaseApp
  after_script:
    - echo "=== PUBLISHING TO GOOGLE PLAY STORE [BETA TRACK RELEASE] ==="    
    - |
      fls-android track --build-number $CI_JOB_ID --package-name $PACKAGE_NAME \
      --bundle-path $BUNDLE_FILE_PATH --track-name beta
    - |      


.publishToProductionTrack:
  stage: deploy
  tags:
    - healthcloud
  only:
    - master  
  extends: .buildRealeaseApp
  after_script:
    - echo "=== PUBLISHING TO GOOGLE PLAY STORE [PRODUCTION TRACK RELEASE] ==="    
    - |
      fls-android track --build-number $CI_JOB_ID --package-name $PACKAGE_NAME \
      --bundle-path $BUNDLE_FILE_PATH --track-name production
    - |       